extends:
  - "@sinonjs/eslint-config"

plugins:
  - "@sinonjs/no-prototype-methods"

rules:
  "@sinonjs/no-prototype-methods/no-prototype-methods": error

globals:
  BigInt: false
  Promise: false
  Int8Array: false
  Uint8Array: false
  Uint8ClampedArray: false
  Int16Array: false
  Uint16Array: false
  Int32Array: false
  Uint32Array: false
  Float32Array: false
  Float64Array: false

overrides:
  - files: "*.test.*"
    rules:
      "@sinonjs/no-prototype-methods/no-prototype-methods": off
      max-nested-callbacks: off
